name: Mindless Rambling Nonsense
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
description: My thoughts are mindless and rambling so the best place for them is the internet
encoding: UTF-8
url: https://pauldambra.dev
author: paul.dambra+fb-instant@gmail.com
excerpt_separator: <!--more-->
ampdir: amp
facebook_id: 1029758320473951
amp_googleanalytics_id: UA-49969634-1
future: true
plugins:
  - octopress-paginate
exclude:
  - node_modules
  - sw-config.js
  - "*.sh"
  - htmltest.rb
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
  - make_collection.py
  - weeknote.rb
  - .vscode
collections:
  dear_diary_year_one:
    output: false
  weeknotes:
    output: true
