name: Mindless Rambling Nonsense
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
description: My thoughts are mindless and rambling so the best place for them is the internet
encoding: UTF-8
url: https://pauldambra.dev
author: paul.dambra+fb-instant@gmail.com
excerpt_separator: <!--more-->
facebook_id: 1029758320473951
future: true
plugins:
  - octopress-paginate
  - jekyll-postcss
keep_files: [images]
exclude:
  - "*.sh"
  - .alexrc
  - .github
  - .gitignore
  - .idea
  - .jekyll-cache
  - .nvmrc
  - .remark*
  - .ruby-version
  - .spelling
  - .vscode
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - htmltest.rb
  - make_collection.py
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - sw-config.js
  - tailwind.config.js
  - vendor
  - weeknote.rb
  - yarn.lock
collections:
  dear_diary_year_one:
    output: false
  weeknotes:
    output: true
